//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipProjesiWeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsTakipEntities : DbContext
    {
        public IsTakipEntities()
            : base("name=IsTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAdmin> TAdmin { get; set; }
        public virtual DbSet<TCagri> TCagri { get; set; }
        public virtual DbSet<TDepartman> TDepartman { get; set; }
        public virtual DbSet<TGorev> TGorev { get; set; }
        public virtual DbSet<TGorevDetay> TGorevDetay { get; set; }
        public virtual DbSet<TPersonel> TPersonel { get; set; }
        public virtual DbSet<TCagriDetay> TCagriDetay { get; set; }
        public virtual DbSet<TFirma> TFirma { get; set; }
    }
}
